server:
  port: 10002

eureka:
  client:
    register-with-eureka: true # 是否注册自己
    fetch-registry: true       # 表是否去注册中心获取其他服务的地址
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: config #搜索目录,当配置文件在git仓库的多级目录中时，需指定，否则SpringCloudConfig默认只会在Git仓库根目录寻找
          # uri: git@github.com:zhangjun101/zj-shop.git #git仓库地址
          # passphrase: 15828411534@163.com #GIT公钥生成时如果设置了密码，则需输入，否则无需配置
          # 这里采用的是https地址访问git
          uri: https://github.com/zhangjun101/zj-shop.git #git仓库地址
          username: 15828411534@163.com #git帐号
          password: zby101908 #git密码
          default-label: main #读取分支(可不配置)