server:
  port: 10002

eureka:
  client:
    register-with-eureka: true # 是否注册自己
    fetch-registry: true       # 表是否去注册中心获取其他服务的地址
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/

spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangjun101/zj-shop.git #配置文件所在仓库
#          username: github #登录账号  公开的git不用登录
#          password: github #登录密码
          default-label: master #配置文件分支
          search-paths: config/src/main/resources/config/**   #配置文件所在根目录（相对于git跟目录，可以使用**进行通配）,多个路径逗号隔开
          basedir: C:\Users\zby\Desktop\zjshopconfig # 对于使用git,svn做为后端配置，从远程库获取配置文件，需要存储到本地文件
          # 配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true