server:
  port: 9040

eureka: 
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/

#开启Hystrix功能
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: pay-server

