server:
  port: 9090

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          ####搜索目录,当配置文件在git仓库的多级目录中时，需指定，否则SpringCloudConfig默认只会在Git仓库根目录寻找
          search-paths:
            - /** #git仓库下所有目录
            - /config/src/main/resources/config #指定目录 有多个路径使用逗号隔开
          uri: git@github.com:zhangjun101/zj-shop.git #git仓库地址
          passphrase: 15828411534@163.com #GIT公钥生成时如果设置了密码，则需输入，否则无需配置
          username: 15828411534@163.com #git帐号
          password: zby101908 #git密码
          default-label: main #读取分支(可不配置)

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/
    register-with-eureka: true #指示此实例是否应将其信息注册到eureka服务器以供其他服务发现，默认为true
    registry-fetch-interval-seconds: 30 #从eureka服务器获取注册表信息的频率（s）
  instance:
    lease-renewal-interval-in-seconds: 30 #该服务实例向注册中心发送心跳间隔（s）
    lease-expiration-duration-in-seconds: 90 #指示eureka服务器在删除此实例之前收到最后一次心跳之后等待的时间（s)
